DROP TABLE IF EXISTS "accounts" CASCADE;
DROP TABLE IF EXISTS "holdings" CASCADE;
DROP TABLE IF EXISTS "plaid_items" CASCADE;
DROP TABLE IF EXISTS "sessions" CASCADE;
DROP TABLE IF EXISTS "transactions" CASCADE;
DROP TABLE IF EXISTS "users" CASCADE;
DROP TABLE IF EXISTS "verifications" CASCADE;
